-define(SERVICE_PORT_TABLE, automate_service_port_table).
-define(SERVICE_PORT_CONFIGURATION_TABLE, automate_service_port_configuration_table).
-define(SERVICE_PORT_CHANNEL_MONITORS_TABLE, automate_service_port_channel_monitors_table).

-define(USER_TO_BRIDGE_CONNECTION_TABLE, automate_service_port_channel_user_to_bridge_connection_table).
-define(USER_TO_BRIDGE_PENDING_CONNECTION_TABLE, automate_service_port_channel_user_to_bridge_pending_connection_table).
-define(SERVICE_PORT_SHARED_RESOURCES_TABLE, automate_service_port_shared_resources_table).
-define(BRIDGE_TOKEN_TABLE, automate_service_port_bridge_token_table).

%% Connections to bridges
-define(CONNECTED_BRIDGES_TABLE, automate_service_port_connected_bridges_table).
-define(ON_FLIGHT_MESSAGES_TABLE, automate_service_port_bridge_on_flight_messages_table).
