-define(SERVICE_PORT_TABLE, automate_service_port_table).
-define(SERVICE_PORT_CONFIGURATION_TABLE, automate_service_port_configuration_table).
-define(SERVICE_PORT_CHANNEL_TABLE, automate_service_port_channel_table).
-define(SERVICE_PORT_CHANNEL_MONITORS_TABLE, automate_service_port_channel_monitors_table).

-define(USER_TO_BRIDGE_CONNECTION_TABLE, automate_service_port_channel_user_to_bridge_connection_table).
-define(USER_TO_BRIDGE_PENDING_CONNECTION_TABLE, automate_service_port_channel_user_to_bridge_pending_connection_table).

%%%% In process of removal
%% -define(SERVICE_PORT_USERID_OBFUSCATION_TABLE, automate_service_port_userid_obfuscation_table).
