{
 "title": "Plaza",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(erlang_vm_process_count, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage",
   "type": "singlestat",
   "description": "Storage supervisor",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "automate_service{name=\"automate_storage_sup\"}"
    }
   ]
  },
  {
   "title": "Channel engine",
   "type": "singlestat",
   "description": "Channel engine supervisor",
   "gridPos": { "h": 1, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "automate_service{name=\"automate_channel_engine_sup\"}"
    }
   ]
  },
  {
   "title": "Monitor engine",
   "type": "singlestat",
   "description": "Monitor engine supervisor",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "automate_service{name=\"automate_monitor_engine_sup\"}"
    }
   ]
  },
  {
   "title": "Bot engine",
   "type": "singlestat",
   "description": "Bot engine supervisor",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "automate_service{name=\"automate_bot_engine_sup\"}"
    }
   ]
  },
  {
   "title": "Failing services",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(automate_service) - sum(automate_service)"
    }
   ]
  },
  {
   "title": "Service registry",
   "type": "singlestat",
   "description": "Service registry supervisor",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "automate_service{name=\"automate_service_registry_sup\"}"
    }
   ]
  },
  {
   "title": "Channel engine monitor",
   "type": "singlestat",
   "description": "Channel engine monitor",
   "gridPos": { "h": 1, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "automate_service{name=\"automate_channel_engine\"}"
    }
   ]
  },
  {
   "title": "Monitor engine runner",
   "type": "singlestat",
   "description": "Monitor engine supervisor",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "automate_service{name=\"automate_monitor_engine_runner_sup\"}"
    }
   ]
  },
  {
   "title": "Bot engine runner",
   "type": "singlestat",
   "description": "Bot engine runner supervisor",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "automate_service{name=\"automate_bot_engine_runner_sup\"}"
    }
   ]
  },
  {
   "title": "REST API",
   "type": "singlestat",
   "description": "REST API supervisor",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "automate_service{name=\"automate_rest_api_sup\"}"
    }
   ]
  },
  {
   "title": "Bridge engine",
   "type": "singlestat",
   "description": "Bridge engine supervisor",
   "gridPos": { "h": 1, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "automate_service{name=\"automate_service_port_engine_sup\"}"
    }
   ]
  },
  {
   "title": "Telegram",
   "type": "singlestat",
   "description": "Telegram supervisor",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "automate_service{name=\"automate_services_telegram_sup\"}"
    }
   ]
  },
  {
   "title": "Telegram demux",
   "type": "singlestat",
   "description": "Telegram demux service",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "automate_service{name=\"automate_services_telegram_demux\"}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Running bots",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "automate_bot_count{state=\"total\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "automate_bot_count{state=\"running\"}",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Running monitors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "automate_monitor_count{state=\"total\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "automate_monitor_count{state=\"running\"}",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Registered users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "automate_user_count", "legendFormat": "Registered" }
   ]
  },
  {
   "title": "Services",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "automate_service_count{visibility=\"all\"}",
     "legendFormat": "All"
    },
    {
     "expr": "automate_service_count{visibility=\"public\"}",
     "legendFormat": "Public"
    }
   ]
  },
  {
   "title": "Bot usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(automate_bot_engine_cycles[$interval]))",
     "legendFormat": "Operations"
    }
   ]
  },
  {
   "title": "Messages passed",
   "type": "graph",
   "description": "Messages getting in and out of the channel_engine",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(automate_channel_engine_messages_in[$interval]))",
     "legendFormat": "Channel engine Fan IN"
    },
    {
     "expr": "sum(rate(automate_channel_engine_messages_out[$interval]))",
     "legendFormat": "Channel engine Fan OUT"
    },
    {
     "expr": "sum(rate(automate_bridge_engine_messages_to_bridge[$interval]))",
     "legendFormat": "Plaza -> Bridge"
    },
    {
     "expr": "sum(rate(automate_bridge_engine_messages_from_bridge[$interval]))",
     "legendFormat": "Bridge -> Plaza"
    }
   ]
  },
  {
   "title": "Evolution #/$interval",
   "type": "graph",
   "description": "Creation rate per minute",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(automate_bot_count{state=\"total\"}[$interval])",
     "legendFormat": "Bots"
    },
    {
     "expr": "rate(automate_monitor_count{state=\"total\"}[$interval])",
     "legendFormat": "Monitors"
    },
    {
     "expr": "rate(automate_service_count{visibility=\"all\"}[$interval])",
     "legendFormat": "Services"
    },
    {
     "expr": "rate(automate_user_count{state=\"registered\"}[$interval])",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Monitor usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(automate_monitor_trigger[10m]))",
     "legendFormat": "Triggers"
    }
   ]
  },
  {
   "title": "Chat channels",
   "type": "graph",
   "description": "Registered chats",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "automate_chat_count", "legendFormat": "Chats" },
    { "expr": "automate_chat_service_count", "legendFormat": "Chat services" }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "OS Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"172.17.0.1:9212\"}",
     "legendFormat": "Virtual memory"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"172.17.0.1:9212\"}",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "Native Threads & CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_threads_total{instance=\"172.17.0.1:9212\"}",
     "legendFormat": "Threads"
    },
    {
     "expr": "sum(irate(process_cpu_seconds_total{instance=\"172.17.0.1:9212\"}[$interval])) without (kind) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "BEAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "VM IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_bytes_output_total{instance=\"$node\"}[$interval])",
     "legendFormat": "Output Bytes"
    },
    {
     "expr": "irate(erlang_vm_statistics_bytes_received_total{instance=\"$node\"}[$interval])",
     "legendFormat": "Received Bytes"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_process_count{instance=\"$node\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "erlang_vm_statistics_run_queues_length_total{instance=\"$node\"}",
     "legendFormat": "Run Queues Length"
    }
   ]
  },
  {
   "title": "VM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{instance=\"$node\", kind=\"processes\"}",
     "legendFormat": "Processes Memory"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"atom\"}",
     "legendFormat": "Atoms"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"binary\"}",
     "legendFormat": "Binary"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"code\"}",
     "legendFormat": "Code"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"ets\"}",
     "legendFormat": "ETS"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_context_switches{instance=\"$node\"}[$interval])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "irate(erlang_vm_statistics_reductions_total{instance=\"$node\"}[$interval])",
     "legendFormat": "Reductions"
    },
    {
     "expr": "irate(erlang_vm_statistics_runtime_milliseconds{instance=\"$node\"}[$interval])",
     "legendFormat": "Runtime"
    }
   ]
  },
  {
   "title": "VM GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs{instance=\"$node\"}[$interval])",
     "legendFormat": "Number of GCs"
    },
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_bytes_reclaimed{instance=\"$node\"}[$interval])",
     "legendFormat": "Bytes Reclaimed"
    }
   ]
  },
  {
   "title": "File Descriptors & Ports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$node\"}",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "process_max_fds{instance=\"$node\"}",
     "legendFormat": "Max FDs"
    },
    {
     "expr": "erlang_vm_port_limit{instance=\"$node\"}",
     "legendFormat": "Max Ports"
    },
    {
     "expr": "erlang_vm_port_count{instance=\"$node\"}",
     "legendFormat": "Ports"
    }
   ]
  },
  {
   "title": "ETS/DETS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_ets_limit{instance=\"$node\"}",
     "legendFormat": "ETS Limit"
    },
    {
     "expr": "erlang_vm_ets_tables{instance=\"$node\"}",
     "legendFormat": "ETS Tables"
    },
    {
     "expr": "erlang_vm_dets_tables{instance=\"$node\"}",
     "legendFormat": "DETS Tables"
    }
   ]
  }
 ]
}