{
 "title": "PrograMaker",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(erlang_vm_process_count, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "backnode",
    "label": "Backend-node",
    "query": "label_values(erlang_vm_process_count,pod) "
   }
  ]
 },
 "panels": [
  {
   "title": "Storage",
   "type": "singlestat",
   "description": "Storage supervisor",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(automate_service{name=\"automate_storage\"})"
    }
   ]
  },
  {
   "title": "Bot engine",
   "type": "singlestat",
   "description": "Bot engine supervisor",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(automate_service{name=\"automate_bot_engine\"})"
    }
   ]
  },
  {
   "title": "Bridge engine",
   "type": "singlestat",
   "description": "Bridge engine supervisor",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(automate_service{name=\"automate_service_port_engine\"})"
    }
   ]
  },
  {
   "title": "Active (Logged last hour)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(automate_logged_users_last_hour)",
     "legendFormat": "People logged last hour"
    }
   ]
  },
  {
   "title": "Service registry",
   "type": "singlestat",
   "description": "Service registry supervisor",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(automate_service{name=\"automate_service_registry\"})"
    }
   ]
  },
  {
   "title": "Bot engine runner",
   "type": "singlestat",
   "description": "Bot engine runner supervisor",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(automate_service{name=\"automate_bot_engine_program_runner\"})"
    }
   ]
  },
  {
   "title": "Channel engine",
   "type": "singlestat",
   "description": "Channel engine supervisor",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(automate_service{name=\"automate_channel_engine\"})"
    }
   ]
  },
  {
   "title": "REST API",
   "type": "singlestat",
   "description": "REST API supervisor",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(automate_service{name=\"automate_rest_api\"})"
    }
   ]
  },
  {
   "title": "Bot engine thread runner",
   "type": "singlestat",
   "description": "Bot engine thread runner supervisor",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(automate_service{name=\"automate_bot_engine_thread_runner\"})"
    }
   ]
  },
  {
   "title": "Bridge count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(automate_bridges_count{visibility=\"public\",pod=\"$backnode\"})",
     "legendFormat": "Public"
    },
    {
     "expr": "min(automate_bridges_count{visibility=\"private\",pod=\"$backnode\"})",
     "legendFormat": "Private"
    }
   ]
  },
  {
   "title": "Bridges connected",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(automate_bridges_unique_connections_count{pod=\"$backnode\"})"
    }
   ]
  },
  {
   "title": "Total registered",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "min(automate_user_count)", "legendFormat": "Registered" }
   ]
  },
  {
   "title": "Unique last week",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(automate_logged_users_last_week)"
    }
   ]
  },
  {
   "title": "Groups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "min(automate_group_count)", "legendFormat": "Groups" }
   ]
  },
  {
   "title": "Programs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(automate_bot_count{pod=\"$backnode\",state=\"workers\"})"
    }
   ]
  },
  {
   "title": "Failing services",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(min(automate_service)) - sum(min(automate_service)) OR on() vector(8)"
    }
   ]
  },
  {
   "title": "Reg. last week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(automate_registered_users_last_week)",
     "legendFormat": "People registered last week"
    }
   ]
  },
  {
   "title": "Created last week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(automate_created_groups_last_week)",
     "legendFormat": "Groups"
    }
   ]
  },
  { "title": "Error generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Program error log count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(automate_program_log_count{severity=\"error\",pod=\"plaza-backend-0\"})",
     "legendFormat": "Program error log count"
    }
   ]
  },
  {
   "title": "Error log generation rate by type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 22, "x": 2, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (log_type) (rate(automate_program_log_count{pod=\"$backnode\",severity=\"error\"}[1h]))",
     "legendFormat": "{{log_type}}"
    }
   ]
  },
  {
   "title": "Error count by type",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (log_type) (automate_program_log_count{pod=\"$backnode\",severity=\"error\"})",
     "legendFormat": "{{log_type}}"
    }
   ]
  },
  {
   "title": "Logs by severity",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (severity) (automate_program_log_count{pod=\"$backnode\"})",
     "legendFormat": "{{log_type}}"
    }
   ]
  },
  { "title": "Programs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Bot usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(automate_bot_engine_cycles[$interval]))",
     "legendFormat": "Operations"
    },
    {
     "expr": "sum(rate(automate_bot_thread_launch[$interval]))",
     "legendFormat": "Threads launched"
    }
   ]
  },
  {
   "title": "Running programs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "avg(automate_bot_count{state=\"running\"})",
     "legendFormat": "Programs running"
    },
    {
     "expr": "avg(automate_bot_count{state=\"total\"})",
     "legendFormat": "Programs total"
    }
   ]
  },
  {
   "title": "Running threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(automate_program_thread_count{state=\"running\"})",
     "legendFormat": "Threads ruinning"
    },
    {
     "expr": "sum(automate_program_thread_count{state=\"total\"})",
     "legendFormat": "Threads total"
    }
   ]
  },
  {
   "title": "Running programs discrepancy",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 32 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "max(automate_bot_count{state=\"running\"}) - min(automate_bot_count{state=\"running\"})",
     "legendFormat": "Programs running"
    },
    {
     "expr": "max(automate_bot_count{state=\"total\"}) - min(automate_bot_count{state=\"total\"})",
     "legendFormat": "Programs total"
    }
   ]
  },
  {
   "title": "Running threads discrepancy",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 32 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "max(automate_program_thread_count{state=\"running\"}) - min(automate_program_thread_count{state=\"running\"})",
     "legendFormat": "Threads ruinning"
    },
    {
     "expr": "max(automate_program_thread_count{state=\"total\"}) - min(automate_program_thread_count{state=\"total\"})",
     "legendFormat": "Threads total"
    }
   ]
  },
  { "title": "Bridge data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Public Bridges",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(automate_bridges_count{visibility=\"public\"})",
     "legendFormat": "Public bridges"
    }
   ]
  },
  {
   "title": "Private Bridges",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(automate_bridges_count{visibility=\"private\"})",
     "legendFormat": "Public bridges"
    }
   ]
  },
  {
   "title": "Messages to/from bridge",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(automate_bridge_engine_messages_from_bridge[$interval]))",
     "legendFormat": "From bridge"
    },
    {
     "expr": "sum(rate(automate_bridge_engine_messages_to_bridge[$interval]))",
     "legendFormat": "To bridge"
    }
   ]
  },
  { "title": "Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Messages passed in channels",
   "type": "graph",
   "description": "Messages getting in and out of the channel and bridge engines",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(automate_channel_engine_messages_in[$interval]))",
     "legendFormat": "Channel engine Fan IN"
    },
    {
     "expr": "sum(rate(automate_channel_engine_messages_out[$interval]))",
     "legendFormat": "Channel engine Fan OUT"
    }
   ]
  },
  { "title": "Monitors &  Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Monitor usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(automate_monitor_trigger[$interval]))",
     "legendFormat": "Triggers"
    }
   ]
  },
  {
   "title": "Running monitors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(automate_monitor_count{state=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "min(automate_monitor_count{state=\"running\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Evolution #/$interval",
   "type": "graph",
   "description": "Creation rate per minute",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(automate_bot_count{state=\"total\"}[$interval]))",
     "legendFormat": "Bots"
    },
    {
     "expr": "avg(rate(automate_monitor_count{state=\"total\"}[$interval]))",
     "legendFormat": "Monitors"
    },
    {
     "expr": "avg(rate(automate_service_count{visibility=\"all\"}[$interval]))",
     "legendFormat": "Services"
    },
    {
     "expr": "avg(rate(automate_user_count{state=\"registered\"}[$interval]))",
     "legendFormat": "Users"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 60 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "OS Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$node\"}",
     "legendFormat": "Virtual memory"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$node\"}",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "Native Threads & CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 60 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_threads_total{instance=\"$node\"}",
     "legendFormat": "Threads"
    },
    {
     "expr": "sum(irate(process_cpu_seconds_total{instance=\"$node\"}[$interval])) without (kind) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "BEAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "VM IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_bytes_output_total{instance=\"$node\"}[$interval])",
     "legendFormat": "Output Bytes"
    },
    {
     "expr": "irate(erlang_vm_statistics_bytes_received_total{instance=\"$node\"}[$interval])",
     "legendFormat": "Received Bytes"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_process_count{instance=\"$node\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "erlang_vm_statistics_run_queues_length_total{instance=\"$node\"}",
     "legendFormat": "Run Queues Length"
    }
   ]
  },
  {
   "title": "VM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{instance=\"$node\", kind=\"processes\"}",
     "legendFormat": "Processes Memory"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"atom\"}",
     "legendFormat": "Atoms"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"binary\"}",
     "legendFormat": "Binary"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"code\"}",
     "legendFormat": "Code"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"ets\"}",
     "legendFormat": "ETS"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_context_switches{instance=\"$node\"}[$interval])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "irate(erlang_vm_statistics_reductions_total{instance=\"$node\"}[$interval])",
     "legendFormat": "Reductions"
    },
    {
     "expr": "irate(erlang_vm_statistics_runtime_milliseconds{instance=\"$node\"}[$interval])",
     "legendFormat": "Runtime"
    }
   ]
  },
  {
   "title": "VM GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs{instance=\"$node\"}[$interval])",
     "legendFormat": "Number of GCs"
    },
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_bytes_reclaimed{instance=\"$node\"}[$interval])",
     "legendFormat": "Bytes Reclaimed"
    }
   ]
  },
  {
   "title": "File Descriptors & Ports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$node\"}",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "process_max_fds{instance=\"$node\"}",
     "legendFormat": "Max FDs"
    },
    {
     "expr": "erlang_vm_port_limit{instance=\"$node\"}",
     "legendFormat": "Max Ports"
    },
    {
     "expr": "erlang_vm_port_count{instance=\"$node\"}",
     "legendFormat": "Ports"
    }
   ]
  },
  {
   "title": "ETS/DETS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_ets_limit{instance=\"$node\"}",
     "legendFormat": "ETS Limit"
    },
    {
     "expr": "erlang_vm_ets_tables{instance=\"$node\"}",
     "legendFormat": "ETS Tables"
    },
    {
     "expr": "erlang_vm_dets_tables{instance=\"$node\"}",
     "legendFormat": "DETS Tables"
    }
   ]
  }
 ]
}