' Just the simple path
@startuml happy-path.png
participant program
participant backend
participant bridge

program -> backend: Run order
backend -> bridge: Run order
... bridge computes response ...
backend <-- bridge: Result
program <-- backend: Result
@enduml

@startuml long-running-operation.png
participant program
participant backend
participant bridge

program -> backend: Run order
backend -> bridge: Run order
... bridge computes response ...
backend -> bridge: Still running?
backend <-- bridge: Yes
... bridge still computes response ...
backend <-- bridge: Result
program <-- backend: Result
@enduml

@startuml failed-operation.png
participant program
participant backend
participant bridge

program -> backend: Run order
backend -> bridge: Run order
... bridge fails ...
backend -> bridge: Still running?
backend <-- bridge: No
program <-- backend: Error
@enduml


@startuml error-on-connection-to-bridge.png
participant program
participant backend
participant bridge

program -> backend: Run order
backend -> bridge: Run order
... bridge connection fails silently ...
backend -X bridge: Still running?
... Timeout time passes ...
program <-- backend: Error
@enduml

@startuml disconnection-to-bridge.png
participant program
participant backend
participant bridge

program -> backend: Run order
backend -> bridge: Run order
... bridge connection fails ...
backend -> backend: Connection failed
program <-- backend: Error
@enduml

@startuml too-long-running-operation.png
participant program
participant backend
participant bridge

program -> backend: Run order
backend -> bridge: Run order
... bridge computes response ...
backend -> bridge: Still running?
backend <-- bridge: Yes
... this repeats MaxTimeouts ...
program <-- backend: Result
backend -> bridge: Cancel

@enduml


@startuml no-bridge-running.png
participant program
participant backend
participant bridge

program -> backend: Run order
destroy bridge

program <-- backend: Error
@enduml
