-define(LIVE_CHANNELS_TABLE, automate_channel_engine_live_channels_table).
-define(LISTENERS_TABLE, automate_channel_engine_listeners_table).
-define(MONITORS_TABLE, automate_channel_engine_monitors_table).
